apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mani
spec:
  serviceName: "mani-mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mani-mongodb
  template:
    metadata:
      labels:
        app: mani-mongodb
    spec:
      containers:
        - name: mani-mongodb
          image: mongo@sha256:c165af1a407eefce644877bf5a59ba3d9ca762e62b4f1723c919dc08dc32f4d0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
              memory: "96Mi"
            limits:
              cpu: "125m"
              memory: "128Mi"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mani-mongodb
  namespace: mani
  labels:
    app: mani-mongodb
spec:
  clusterIP: None
  selector:
    app: mani-mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
