{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-metadata.jar",
          "url": "compose-charts-0.0.17-js.jar",
          "size": 31068,
          "sha512": "e0994fe7b58dce9b6aa1e3550c948eb7f516a65ce5b54ecc518e10ad5dd719158c5d81ab703eac3ff791796b11d2567eded6be3f1e159b73dee77d55e9587d7d",
          "sha256": "37f688a0e177dc6b3ec6435eba992bece1312c7ccbeb406458eaf79c83c8feba",
          "sha1": "741722ec04e8952734cc710f41d44afbc55317e4",
          "md5": "85943b8dbfbc487d066fc1ef5c00708d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "compose-charts-kotlin-sources.jar",
          "url": "compose-charts-0.0.17-js-sources.jar",
          "size": 36345,
          "sha512": "c6ab5a87fbfb16942648384b6b5853ed6bec3a1dcfa2b1dd60cd3e5a339fb13b9cad6a1cb50e60a8e3f1024e0c63c4b1b6a6c307a9acbf686f2fe3c70ecc37a1",
          "sha256": "f66092daebcec929c3da5631ca3ffe1d3c988c778125fbed4c4139946b302eb9",
          "sha1": "2d2a1503a9988187619cf8e6f4e0ed75dc6a94b5",
          "md5": "ab7de5da59031b8994be2a2913e5bae7"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android-debug/0.0.17-js/compose-charts-android-debug-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android-debug",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android-debug/0.0.17-js/compose-charts-android-debug-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android-debug",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android-debug/0.0.17-js/compose-charts-android-debug-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android-debug",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android/0.0.17-js/compose-charts-android-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android/0.0.17-js/compose-charts-android-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../compose-charts-android/0.0.17-js/compose-charts-android-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-android",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-charts-desktop/0.0.17-js/compose-charts-desktop-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-desktop",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-charts-desktop/0.0.17-js/compose-charts-desktop-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-desktop",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../compose-charts-desktop/0.0.17-js/compose-charts-desktop-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-desktop",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosarm64/0.0.17-js/compose-charts-iosarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosarm64/0.0.17-js/compose-charts-iosarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosarm64/0.0.17-js/compose-charts-iosarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosarm64/0.0.17-js/compose-charts-iosarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iossimulatorarm64/0.0.17-js/compose-charts-iossimulatorarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iossimulatorarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iossimulatorarm64/0.0.17-js/compose-charts-iossimulatorarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iossimulatorarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iossimulatorarm64/0.0.17-js/compose-charts-iossimulatorarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iossimulatorarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iossimulatorarm64/0.0.17-js/compose-charts-iossimulatorarm64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iossimulatorarm64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosx64/0.0.17-js/compose-charts-iosx64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosx64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosx64/0.0.17-js/compose-charts-iosx64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosx64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosx64/0.0.17-js/compose-charts-iosx64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosx64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../compose-charts-iosx64/0.0.17-js/compose-charts-iosx64-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-iosx64",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../compose-charts-js/0.0.17-js/compose-charts-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../compose-charts-js/0.0.17-js/compose-charts-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../compose-charts-js/0.0.17-js/compose-charts-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../compose-charts-js/0.0.17-js/compose-charts-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../compose-charts-wasm-js/0.0.17-js/compose-charts-wasm-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-wasm-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../compose-charts-wasm-js/0.0.17-js/compose-charts-wasm-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-wasm-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../compose-charts-wasm-js/0.0.17-js/compose-charts-wasm-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-wasm-js",
        "version": "0.0.17-js"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../compose-charts-wasm-js/0.0.17-js/compose-charts-wasm-js-0.0.17-js.module",
        "group": "io.github.ehsannarmani",
        "module": "compose-charts-wasm-js",
        "version": "0.0.17-js"
      }
    }
  ]
}
