{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-charts/0.0.17-js/compose-charts-0.0.17-js.module",
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.klib",
          "url": "compose-charts-iossimulatorarm64-0.0.17-js.klib",
          "size": 241379,
          "sha512": "93d62d1313b5be480748066fd8b6a2bb95b5c8f8c7fbfb816e2e77fde24c530be14e5e1c8e59c5e52b766c9884d60560bbe585d86d41ccdb1d852e5d7c8da915",
          "sha256": "f052bc667db28f09655740d2a35fa783c426b7979694b8eb98179ce98219cc97",
          "sha1": "cc0abb351d3a8b8fb2eec2a603925951e41c0435",
          "md5": "2f54a7846a57d5983dffd7e0e3f44aad"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-charts-iossimulatorarm64-sources.jar",
          "url": "compose-charts-iossimulatorarm64-0.0.17-js-sources.jar",
          "size": 36345,
          "sha512": "00f95c1fa5e6295cb2f635adbf57a574e32fde48201057c94ee7e5c46f6bd251679342179c4dcec623bded6f9c976f72bb75066c6cf177844e3bc924c284c1ae",
          "sha256": "40132c6171474942df53613b97083c9dc5d8543ac338c4c8f1109e34e2090f79",
          "sha1": "a24b302a47f594b913e37bb508ef9ee26e83fa24",
          "md5": "e1264640eb0b6992b041003594c5bbb5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.kotlin_resources.zip",
          "url": "compose-charts-iossimulatorarm64-0.0.17-js-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "d4984aeef94d2fe804c12b42bdfb1359a2f8324b7df0897af47b864be3c9e8faba30ede9ac75312dae8ea5ac299375a0ac133b9ff93ef2f1e32b9256d17cb83e",
          "sha256": "817d5249a51dcf0cd00b3fbe7b4f30eb2e119b6f636a312a9acde33328736b2e",
          "sha1": "1da95f8c10bcc5be11fb1030f0063141c42e7323",
          "md5": "c962465103825febea6e1739ba2e09c4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-iossimulatorarm64-metadata.jar",
          "url": "compose-charts-iossimulatorarm64-0.0.17-js-metadata.jar",
          "size": 2783,
          "sha512": "8effe34a7e41c0c508a7a6271fbc94402418f40ca4d12a43d6b5450747f1116f3fbc1d9e141250e51d36f6325ca1950f621a721145d973d086c57832a0e1cf3b",
          "sha256": "33711798134534163b76014701f6abee4b2cea6ef8e6c6f69b958791b8ad83c4",
          "sha1": "8eabdfd46d7de4861e9ec7d04752b1e29709b7c8",
          "md5": "afac3811568c219847c9d44cbc36f332"
        }
      ]
    }
  ]
}
