{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-charts/0.0.17-js/compose-charts-0.0.17-js.module",
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-wasm-js.klib",
          "url": "compose-charts-wasm-js-0.0.17-js.klib",
          "size": 3492884,
          "sha512": "ef2d5064b325087e3f871511844e1a599c70a3a60895b1606a9af7e7336b93be762fb2e129a973069ccbec3c21fc846dc8a0319c1e0c9e728087e29888df36e3",
          "sha256": "e866745b37951d09997781527d5dd45c52b4a1d3631b87ff1f8afd1af54301e8",
          "sha1": "ab4bf78c0353756b70f0070b29291698ed300164",
          "md5": "e3eb53d59a218650294c3768d1e3127a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-wasm-js.klib",
          "url": "compose-charts-wasm-js-0.0.17-js.klib",
          "size": 3492884,
          "sha512": "ef2d5064b325087e3f871511844e1a599c70a3a60895b1606a9af7e7336b93be762fb2e129a973069ccbec3c21fc846dc8a0319c1e0c9e728087e29888df36e3",
          "sha256": "e866745b37951d09997781527d5dd45c52b4a1d3631b87ff1f8afd1af54301e8",
          "sha1": "ab4bf78c0353756b70f0070b29291698ed300164",
          "md5": "e3eb53d59a218650294c3768d1e3127a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "compose-charts-wasm-js-sources.jar",
          "url": "compose-charts-wasm-js-0.0.17-js-sources.jar",
          "size": 36345,
          "sha512": "829422a57fc2082331069f72068bcf49585341eb85165ecae36b3704157cd903312713b59209367bcad8ec62a71455237edfb964abc4222b756ae6cd1735003d",
          "sha256": "9796d5a072ddb063fc4939cccea8f08e002c86385e33702b7475fd52b788c9b5",
          "sha1": "1e70328b0ab034ac7d1be0edf1be007f9312d5f4",
          "md5": "8318e6e05ab389f55dec3777acf32dbc"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.kotlin_resources.zip",
          "url": "compose-charts-wasm-js-0.0.17-js-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "605a062905ffd05bf1b2631ae724828729432f99e343a02e95ce655370fb737122988996622ffd49b33e7681a61d586d4ea312ca4c526ac8bf5b51500d0e9c80",
          "sha256": "4b4554a0aa15009d86b9bf93487c3f9278625ad215c19b7d4fe0648b8b90e532",
          "sha1": "000b1b0a0ce36b61b9748534d52f36b80c6df218",
          "md5": "087f33dfbf089e7af3bed1349c7f688c"
        }
      ]
    }
  ]
}
