{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-charts/0.0.17-js/compose-charts-0.0.17-js.module",
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.klib",
          "url": "compose-charts-iosarm64-0.0.17-js.klib",
          "size": 241292,
          "sha512": "3a6f5f1029d416821ffc958c9d8758462d33f5e51be92dc46d7236bd7c8dcd8e1ecb4df51fabecf94697034bc8a74828325343bfbac2e1b76c59b1d607ea0f0a",
          "sha256": "8143ce5ed6a30e383509f6679caf832d91c64a4e097b0f8026234b397363986e",
          "sha1": "1927d363aa71bbcf22457848e05300e3cc239a8a",
          "md5": "1408835e90e90ce0eca5e8058a362084"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-charts-iosarm64-sources.jar",
          "url": "compose-charts-iosarm64-0.0.17-js-sources.jar",
          "size": 36345,
          "sha512": "00f95c1fa5e6295cb2f635adbf57a574e32fde48201057c94ee7e5c46f6bd251679342179c4dcec623bded6f9c976f72bb75066c6cf177844e3bc924c284c1ae",
          "sha256": "40132c6171474942df53613b97083c9dc5d8543ac338c4c8f1109e34e2090f79",
          "sha1": "a24b302a47f594b913e37bb508ef9ee26e83fa24",
          "md5": "e1264640eb0b6992b041003594c5bbb5"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.kotlin_resources.zip",
          "url": "compose-charts-iosarm64-0.0.17-js-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "15ae4bb39d7b7629be12f6258890c810357b5da3533a4e2f9e071eb34997340483a32c70a5e3bd441f4b6a15c1b954d30bfdcb5a48f0e6730f459fcc8c2448b4",
          "sha256": "25fcafb4575d9f1fec3f26b58db6d77eed60621801463e9ec4f6f77af2f103f5",
          "sha1": "d24132d8b959a764dfebbb5eb39026f30bb86411",
          "md5": "98f7612b02046b2c0308e7eb0b308f78"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-iosarm64-metadata.jar",
          "url": "compose-charts-iosarm64-0.0.17-js-metadata.jar",
          "size": 2783,
          "sha512": "8bb0fc2703d63dc59781ea43f115936eeabf9a1f76b97d976a65b69b1b20b04b95f95e50b93f38a31f9b6ca45516849afac101c5c74542ce4148aee81beb0fdf",
          "sha256": "a81a5fb69d24f0bbd85d7d5bff04d46e7abbcbb1e2f14f4cc86128970f3496e7",
          "sha1": "4cad4eeade644a7a9a36e5a2fb5569822447c295",
          "md5": "982e14d2370584975efa5b58ee9b7b64"
        }
      ]
    }
  ]
}
