{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-charts/0.0.17-js/compose-charts-0.0.17-js.module",
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-js.klib",
          "url": "compose-charts-js-0.0.17-js.klib",
          "size": 3492885,
          "sha512": "4a7c3d386dbbcbf678e076380e6223c842f331efb87ab71b4838cf211142ccf5fe58b409466f5366c27b4612520a81c8054b7cd6a8d02aa35f01b97230c2219c",
          "sha256": "08dcaeab04d191714ec5e8d8cfb53dff839467e71b38b27fe98a7344ebcd439c",
          "sha1": "c40a8c532b3e928b14f0c3b3a7975cad65b23b6b",
          "md5": "a546504415019071b009d44ceb92f830"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-js.klib",
          "url": "compose-charts-js-0.0.17-js.klib",
          "size": 3492885,
          "sha512": "4a7c3d386dbbcbf678e076380e6223c842f331efb87ab71b4838cf211142ccf5fe58b409466f5366c27b4612520a81c8054b7cd6a8d02aa35f01b97230c2219c",
          "sha256": "08dcaeab04d191714ec5e8d8cfb53dff839467e71b38b27fe98a7344ebcd439c",
          "sha1": "c40a8c532b3e928b14f0c3b3a7975cad65b23b6b",
          "md5": "a546504415019071b009d44ceb92f830"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "compose-charts-js-sources.jar",
          "url": "compose-charts-js-0.0.17-js-sources.jar",
          "size": 35661,
          "sha512": "adf92f326f50b5be932db16e310666f19f7ea0fad1070cd3550d44a5083353f2c414972e191dea1831504221d0b37c40eabcc5c4a305607190bc0a725d745c9c",
          "sha256": "f5494ec7adbddaed4ad6b322a1869c43d4689cdbbdb42d3df2479685ea41f412",
          "sha1": "f57975f3bc302459475f00760f517dee28029a5a",
          "md5": "797b54a0930ccaa6fadc6efc17e2752f"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.kotlin_resources.zip",
          "url": "compose-charts-js-0.0.17-js-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "6bfa47ca95cb370e9c94d7b3501d684a1f90a5c063eea5eab79addc3569d316b7e19a4dde50fdf0aed22e336ce96572e227434148db41d7c9359778e60221550",
          "sha256": "ae6881de6cd4184dab91bd9ef3693bc1fbdd73f8a80690449d0abbca34b18840",
          "sha1": "6de705dc5f60544f018561427b81bfba672f0bac",
          "md5": "2a7cd313f977b65896cd358b67ecb716"
        }
      ]
    }
  ]
}
