{
  "formatVersion": "1.1",
  "component": {
    "url": "../../compose-charts/0.0.17-js/compose-charts-0.0.17-js.module",
    "group": "io.github.ehsannarmani",
    "module": "compose-charts",
    "version": "0.0.17-js",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.klib",
          "url": "compose-charts-iosx64-0.0.17-js.klib",
          "size": 241275,
          "sha512": "32337080727ab2cf1feb5ea6b3cd9d202402b13fa0c2abe4fd3f3cab0baf5e0288c980e0cede6dafe25f32832970eab0f26339b1296874c42022d065fc714624",
          "sha256": "4a42f261b098d191eca74ae635430477ffbf71dbb27ac7123346b19740a817e3",
          "sha1": "89aa627031eb7eb94f2c7dbbe9c49edf8d17ad69",
          "md5": "f9285ec86528d0c4264867efb3016659"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "compose-charts-iosx64-sources.jar",
          "url": "compose-charts-iosx64-0.0.17-js-sources.jar",
          "size": 36345,
          "sha512": "00f95c1fa5e6295cb2f635adbf57a574e32fde48201057c94ee7e5c46f6bd251679342179c4dcec623bded6f9c976f72bb75066c6cf177844e3bc924c284c1ae",
          "sha256": "40132c6171474942df53613b97083c9dc5d8543ac338c4c8f1109e34e2090f79",
          "sha1": "a24b302a47f594b913e37bb508ef9ee26e83fa24",
          "md5": "e1264640eb0b6992b041003594c5bbb5"
        }
      ]
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts.kotlin_resources.zip",
          "url": "compose-charts-iosx64-0.0.17-js-kotlin_resources.kotlin_resources.zip",
          "size": 344,
          "sha512": "d649a9c51bc0cc0a6600534fb62b8eacf677ce7d2df9c7f4038e5073ebedca14a52b88df2459f4533c283188ab2f4fa163f1fa128ea675a49851644b212da787",
          "sha256": "dea95370c0ae8dd0401baa9d3e6e6b1f296b7364c1a50490b31672c5d07c9c82",
          "sha1": "985449657e96496fed90910f31331889cfc94cf6",
          "md5": "476f64bf9ddaf8affb2f2ece2885815f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.6.11"
          }
        }
      ],
      "files": [
        {
          "name": "compose-charts-iosx64-metadata.jar",
          "url": "compose-charts-iosx64-0.0.17-js-metadata.jar",
          "size": 2783,
          "sha512": "2862f8f6c96383618463c56944cf86d6b203683d57751b0b39966e0120b7d698e0fd5a1370b1d4f3f5eed35f1369e0e1ddaa43dbc342f6dd84ad9e2c95161a1c",
          "sha256": "3b55197cbb71d273762257c845ca08dcbb24ab08c7345fc14cc45c9680f8ff34",
          "sha1": "2004e6ae2c801b325084a5d91a0206d844f18c0c",
          "md5": "fb5942be7d18e44d09eb216c4baa3a80"
        }
      ]
    }
  ]
}
